In [2]:
import pandas as pd

df = pd.read_csv("../data/raw/credit_risk_dataset.csv")
df.shape

(32581, 12)

In [ ]:
df.head() #The first few rows of the dataset are displayed below:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

In [ ]:
df.info() #Summary of the dataset is displayed below:

<class 'pandas.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  str
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  str
 5   loan_grade                  32581 non-null  str
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  str
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), str(4)
memory usage: 3.0 MB

In [5]:
df.describe() #Statistical summary of the dataset is displayed below:

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [6]:
print(df.isna().sum()) #The number of missing values in each column is displayed below:

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [7]:
print("Duplicate rows:", df.duplicated().sum()) #The number of duplicate rows in the dataset is displayed below:

Duplicate rows: 165

In [8]:
for col in df.select_dtypes(include=['object']).columns:
    print(df[col].value_counts(dropna=False), "\n") #The unique values and their counts for each categorical column are displayed below:

person_home_ownership
RENT        16446
MORTGAGE    13444
OWN          2584
OTHER         107
Name: count, dtype: int64

loan_intent
EDUCATION            6453
MEDICAL              6071
VENTURE              5719
PERSONAL             5521
DEBTCONSOLIDATION    5212
HOMEIMPROVEMENT      3605
Name: count, dtype: int64

loan_grade
A    10777
B    10451
C     6458
D     3626
E      964
F      241
G       64
Name: count, dtype: int64

cb_person_default_on_file
N    26836
Y     5745
Name: count, dtype: int64

C:\Users\mezen\AppData\Local\Temp\ipykernel_2856\591294320.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  for col in df.select_dtypes(include=['object']).columns:

In [ ]:
df[df["person_age"]> 100] #The rows where age is greater than 100 are displayed below:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
81,144,250000,RENT,4.0,VENTURE,C,4800,13.57,0,0.02,N,3
183,144,200000,MORTGAGE,4.0,EDUCATION,B,6000,11.86,0,0.03,N,2
575,123,80004,RENT,2.0,EDUCATION,B,20400,10.25,0,0.25,N,3
747,123,78000,RENT,7.0,VENTURE,B,20000,NaN,0,0.26,N,4
32297,144,6000000,MORTGAGE,12.0,PERSONAL,C,5000,12.73,0,0.00,N,25

In [11]:
df[df["person_emp_length"]> 60] #The rows where employment length is greater than 60 are displayed below:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
210,21,192000,MORTGAGE,123.0,VENTURE,A,20000,6.54,0,0.10,N,4

Need to remove person_age > 100 (5 rows)
Need to remove person_emp_length > 60 (2 rows)

In [12]:
df[df["person_emp_length"] > (df["person_age"] - 14 )] 
#The rows where employment length is greater than age minus 14 are displayed below:
#Assumes no one can start working before the age of 14, which is a reasonable assumption for this dataset.

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
210,21,192000,MORTGAGE,123.0,VENTURE,A,20000,6.54,0,0.10,N,4

In [13]:
df.sort_values("person_income", ascending=False).head(10) 
#The top 10 rows with the highest income are displayed below:

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
32297,144,6000000,MORTGAGE,12.0,PERSONAL,C,5000,12.73,0,0.00,N,25
30049,42,2039784,RENT,0.0,VENTURE,C,8450,12.29,0,0.00,Y,15
32546,60,1900000,MORTGAGE,5.0,PERSONAL,A,1500,NaN,0,0.00,N,21
32497,63,1782000,RENT,13.0,EDUCATION,C,12025,14.27,0,0.01,N,30
31924,44,1440000,MORTGAGE,7.0,DEBTCONSOLIDATION,A,6400,7.40,0,0.00,N,15
31922,47,1362000,MORTGAGE,9.0,VENTURE,A,6600,7.74,0,0.00,N,17
29120,40,1200000,MORTGAGE,1.0,MEDICAL,A,10000,NaN,0,0.01,N,16
17833,32,1200000,MORTGAGE,1.0,VENTURE,A,12000,7.51,0,0.01,N,8
29119,36,1200000,OWN,16.0,MEDICAL,A,10000,6.54,0,0.01,N,11
17834,34,948000,MORTGAGE,18.0,PERSONAL,B,2000,9.99,0,0.00,N,7

Apart from the 144 year old making 6,000,000 which will be removed, the rest of the individuals seem like plausible earners, though very high. 
Row 30049 is suspicous with an income on 2,000,000 with 0 years of employment but they may a business owner or investor, so this is not a clear error.

In [14]:
print(df.isna().sum()) #The number of missing values in each column is displayed below:

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

The missing values of 3116 and 895 together is about 12.5% of my dataset, so leaving this data out may affect my results. I will instead use the median for both columns and add a flag column to tell the real values from the filled-in ones.

In [19]:
df_clean = df.copy() 
#Create a copy of the original dataframe to clean and preprocess

In [20]:
df_clean = df_clean.drop_duplicates(keep='first')
#drop duplicate rows, keeping the first occurrence

In [21]:
df_clean = df_clean[df_clean["person_age"] <= 100]
#Remove rows where age is greater than 100 (impossible ages of 123 and 144 years old)

In [22]:
# Keep rows where employment length is 60 or below, OR where it is missing
# Each condition needs its own brackets () so they combine into one filter
# The whole condition sits inside ONE pair of square brackets []
df_clean = df_clean[(df_clean["person_emp_length"] <= 60) | (df_clean["person_emp_length"].isna())]

In [23]:
#Add flag columns to indicate missing values in the "person_emp_length" and "loan_int_rate" columns
df_clean["emp_length_missing"] = df_clean["person_emp_length"].isna().astype(int)
df_clean["int_rate_missing"] = df_clean["loan_int_rate"].isna().astype(int)

In [24]:
df_clean["person_emp_length"] = df_clean["person_emp_length"].fillna(df_clean["person_emp_length"].median())
df_clean["loan_int_rate"] = df_clean["loan_int_rate"].fillna(df_clean["loan_int_rate"].median())
# Fill missing values in the "person_emp_length" and "loan_int_rate" columns with the median of each column

In [25]:
df_clean = df_clean.reset_index(drop=True) #Reset the index of the cleaned dataframe

These last 6 lines of code have been used to create a working copy of the raw data ("df_clean") adjusted for the following:
- Removed the 165 duplicate rows
- Removed the 5 rows of impossible ages that have been deemed as data entry errors 
- Removed the 2 rows which impossible employment lengths 
- Flagged and filled missing values with median values 
- Reset the row numbers after removing rows

In [26]:
print("Rows before cleaning:", df.shape[0])
print("Rows after cleaning:", df_clean.shape[0])
#Compare the number of rows before and after cleaning to see how many rows were removed during the cleaning process

Rows before cleaning: 32581
Rows after cleaning: 32409

The row count matches exactly 32,581 - 32,409 = 172, which is the 165 duplicates + the 5 impossible ages + the 2 impossible employment lengths.

In [27]:
print("Missing values:", df_clean.isna().sum().sum()) 
#Confim that there are no missing values in the cleaned dataframe by summing the number of missing values across all columns

Missing values: 0

In [ ]:
print("Duplicates:", df_clean.duplicated().sum())
#Confirm that there are no duplicate rows in the cleaned dataframe by summing the number of duplicate rows

Duplicates: 0

In [ ]:
print("Max age:", df_clean["person_age"].max())
print("Max employment length:", df_clean["person_emp_length"].max())
#Confirm impossible values are gone by checking the maximum values of age and employment length

Max age: 94
Max employment length: 41.0

In [31]:
print(df_clean[["emp_length_missing", "int_rate_missing"]].sum())
#Confirm the flag columns recorded the correct number of missing values in the "person_emp_length" and "loan_int_rate" columns

emp_length_missing     887
int_rate_missing      3094
dtype: int64

The flag counts for the two columns with missing data are 887 and 3094, slightly below the original 895 and 3116

In [32]:
import os
os.makedirs("../data/processed", exist_ok=True) 
#Create the processed data directory if it doesn't exist
df_clean.to_csv("../data/processed/credit_risk_dataset_cleaned.csv", index=False)
#Save the cleaned dataframe to a new CSV file in the processed data directory(the raw file is not overwritten, and the cleaned data is saved in a separate file for future use)
print("Saved:", pd.read_csv("../data/processed/credit_risk_dataset_cleaned.csv").shape)
#Confirm that the cleaned dataframe was saved correctly by reading it back in and printing its shape

Saved: (32409, 14)

The new file is saved with two extra columns (flag columns) added, hence why the column count went from 12 to 14. 
- If columns in person_emp_length (employment length) and loan_int_rate (interest rate) were left blank the columns will have the number 1. 
- If they had real values they will have the number 0

In [33]:
df_clean[df_clean["int_rate_missing"] == 1][["loan_int_rate", "int_rate_missing"]].head()
#The first few rows of the cleaned dataframe where the "loan_int_rate" was originally missing are displayed below, along with the corresponding flag column "int_rate_missing".

    loan_int_rate  int_rate_missing
38          10.99                 1
49          10.99                 1
56          10.99                 1
58          10.99                 1
61          10.99                 1

In [34]:
df_clean[df_clean["emp_length_missing"] == 1][["person_emp_length", "emp_length_missing"]].head()
#The first few rows of the cleaned dataframe where the "person_emp_length" was originally missing are displayed below, along with the corresponding flag column "emp_length_missing".

     person_emp_length  emp_length_missing
103                4.0                   1
218                4.0                   1
375                4.0                   1
403                4.0                   1
404                4.0                   1

The median values are 10.99 and 4.0 with the flag columns filled with 1 as these are the missing values.